### ISSUE TITLE
The Second MPL Violation

### ISSUE THREAD

**Issue by mattatobin** [Feodor2/Centaury#39]
You are, [once again](https://github.com/Feodor2/Mypal/issues/35), in violation of the `Mozilla Public License 2.0`. Specifically `Section 3.2 Paragraph A`. You have failed to notify recipients of `Covered Code` in `Executable Form` where they may obtain the `Source Code Form` by reasonable means.

Under `Section 5.1` and since this is your second time disobeying the license terms for `Covered Code` **I hereby terminate the grant to use code of which I have contributed.**

You must remove such `Covered Code` from any future distribution and remove offending `Executable Forms` currently in existence. There shall be no further negotiation on this point. You can only come back into compliance with the Mozilla Public License 2.0 by doing this.

**Comment by Feodor2** [comment]
Duplicate issue not necessary

**Comment by Feodor2** [comment]
Sure you may say that you cannot finde a duplicate issue ans instruction
For you personally
1. Install git (go to the site https://git-scm.com/ look thre instruction how to install it)
2. execute git clone https://github.com/Feodor2/Mypal.git
3. execute git checkout Centaury_Release or git checkout cent-mingw
Enjoy
enjoy then

**Comment by mattatobin** [comment]
No, you cannot get off the hook this easily. My issue is you have failed to comply with the MPL for a second time. Centaury uses code I created or contributed to and you cannot simply point me to mypal source code and tell me to piss off this time.

**The rights granted under this License will terminate automatically if You fail to comply with any of its terms.** However, if You become compliant, then the rights granted under this License from a particular Contributor are reinstated (a) provisionally, unless and until **such Contributor explicitly and finally terminates Your grants**, and (b) on an ongoing basis, if such Contributor fails to notify You of the non-compliance by some reasonable means prior to 60 days after You have come back into compliance. Moreover, Your grants from a particular Contributor are reinstated on an ongoing basis if **such Contributor notifies You of the non-compliance** by some reasonable means, **this is the first time You have received notice of non-compliance with this License from such Contributor**, and You become compliant prior to 30 days after Your receipt of the notice.

This is not the first time you have failed to comply nor have you actually done anything to come back into compliance. I have terminated your grant for repeated violations on Section 3.2 Paragraph A due to this which means you no longer entitled to use code I have contributed.

**Comment by JeanPaulLucien** [comment]
@mattatobin 
https://addons.mozilla.org/ru/firefox/addon/russian-ru-language-pack/
Send your claim to Mozilla. They break their own terms.

**Comment by mattatobin** [comment]
How is that?

**Comment by acoolstraw** [comment]
go fuck yourself matt

**Comment by acoolstraw** [comment]
eat shit you fucking vulture

**Comment by h4xor666** [comment]
@mattatobin please get a real job

**Comment by highbaser** [comment]
Thank you for killing this project, @mattatobin. You can be very proud of yourself. You could have put your energy into helping @Feodor2 compy with the license terms still you could only played your idealist legal-minded threatening games. Tens of thousands of users now will have no alternative for their Windows XP boxes to use an up-to-date browser, thanks to you.

**Comment by rubyFeedback** [comment]
I think that ship has already sailed - the three core devs from palemoon have been killing the project. It's not just the Feodor2 situation or the perma-ban against JustOff (before they sneakily modified his extensions without even notifying him; this is, IMO, malware injection 2.0 similar to what sourceforge did a few years ago); I was banned the moment I wrote an orthogonal opinion against Moonchild, in particular how he behaved on the webforum (that PsychoTobin is psycho is known by everyone). At that point I think Moonchild is simply deliberately trolling us, so people need to stop wasting time with him really.

The MUCH more interesting and important thing is ... what to do next? Palemoon, for whatever the reason, is being killed by the old devs. I don't know why, perhaps Google bribed them, but whatever - we need a real alternative. The Google Empire keeps on marching forward and subjugates everyone under the adChromium code base. THAT is the real problem; the in-fighting, e. g. the three PM devs, are ultimately just distractions.

We kind of need a super modular code base, where people are in charge rather than ANY devs (the three PM devs did the same thing as Mozilla did years ago by the way; and Google pays Mozilla these days, so firing 25% of the devs is not an "accident". These are deliberate moves to kill off competitors done by trojan-horse CEOs).

We need real alternatives. C++ unfortunately means that many people can not cope with any of this; JavaScript is a mess and keeps on being shaped up by Google (don't buy into W3C, they are paid by the membership fee cronies, so it's just a cash cow machine rather than a "standard" For The People, By The People").

We need alternatives. THAT is the key issue, not the distractions by the crazy PM devs. We all could see PM no longer working on some websites. This is planned deprecation by the PM devs, we can all see it.

**Comment by shakeyourbunny** [comment]
Palemoon is not dead, that is just a fantasy for some people.

**Comment by SoftwareRat** [comment]
> You are, [once again](https://github.com/Feodor2/Mypal/issues/35), in violation of the `Mozilla Public License 2.0`. Specifically `Section 3.2 Paragraph A`. You have failed to notify recipients of `Covered Code` in `Executable Form` where they may obtain the `Source Code Form` by reasonable means.
> 
> Under `Section 5.1` and since this is your second time disobeying the license terms for `Covered Code` **I hereby terminate the grant to use code of which I have contributed.**
> 
> You must remove such `Covered Code` from any future distribution and remove offending `Executable Forms` currently in existence. There shall be no further negotiation on this point. You can only come back into compliance with the Mozilla Public License 2.0 by doing this.

I see you never touched grass or woman. Help this guy of instead of playing wannabe-lawyer in your basement.

> I hereby terminate the grant to use code of which I have contributed.
shut up, nobody cares about ur opinion

**Comment by mattatobin** [comment]
Right, I should have updated this issue as well.. Sorry, I hereby restore the grant for my contributions to covered code on the on the grounds that @Feodor2 be more careful next time about following the terms of the MPL 2.0.

**Comment by JeanPaulLucien** [comment]
@mattobin too late. You preferred to not read MPL 2.0 and Mozilla Comments. Was it good price for your reputation?

**Comment by mattatobin** [comment]
While I was within my rights under the MPL the implementation OF those rights was somewhat misguided. But if you don't want to accept someone can change course then so be it. It is merely there to be taken or left.

Good day, sir.

**Comment by Bin-2** [comment]
PM old devs' drama never disappointed me.

**Comment by mattatobin** [comment]
Seems to me, the drama never ended in lunar orbit. In fact, seems to be getting worse but that could be that I only read the forums very rarely rather than every damned post checking multiple times a day. 

Yes, for years, I had the entire Pale Moon forum running through my head. I knew every post (from 2014 on), every duplicate, every moderated change because I read it before it happened.

I do NOT recommend it.
